### ISSUE TITLE
「動画を検索」ボタンを押すとエラーになります。

### ISSUE THREAD

**Issue by iwaseasahi** [haru16-no14/Videomarker#5]
## 背景
面接準備のためにポートフォリオの動作確認したところ、エラーになりました。

## URL
https://videomarker.herokuapp.com/videos/new

## スクショ
<img width="1233" alt="スクリーンショット 2020-04-02 11 50 16" src="https://user-images.githubusercontent.com/17666221/78205886-4d7cbd80-74d8-11ea-9151-f6b2b27d6859.png">

<img width="1234" alt="スクリーンショット 2020-04-02 11 50 06" src="https://user-images.githubusercontent.com/17666221/78205895-52da0800-74d8-11ea-83f4-1e962a9034ed.png">

**Comment by iwaseasahi** [comment]
@haru16-no14 
今後の就職活動のために直した方が良いですね 😄

**Comment by komachi16** [comment]
@iwaseasahi 様
ご指摘ありがとうございます。
こちらの方でもGoogleChrome・Safari・Firefoxにて確認させていただいたのですが、いずれも画像の通り正常に動作致しました。

herokuのlogにもエラーに関する記載が見当たらず、原因を特定できておりません。
使用するブラウザで違いが生じる可能性を考えているのですが、使用機器の都合上、IEでの動作を確認できておりません。
もしご迷惑でなければ、お使いのブラウザをお教えいただけますでしょうか。

[![Screenshot from Gyazo](https://gyazo.com/344e907fa64c07a16f3123702bbcc3f6/raw)](https://gyazo.com/344e907fa64c07a16f3123702bbcc3f6)

**Comment by iwaseasahi** [comment]
@haru16-no14 
ブラウザは chrome です。
バージョン: 80.0.3987.149（Official Build） （64 ビット）

**Comment by iwaseasahi** [comment]
@haru16-no14 
今、動作確認したら動きましたね。失礼しました。

<img width="1238" alt="スクリーンショット 2020-04-02 19 14 57" src="https://user-images.githubusercontent.com/17666221/78237418-44aadc80-7516-11ea-8cf3-0d0866468f6d.png">

**Comment by iwaseasahi** [comment]
@haru16-no14 
ちなみにポートフォリオは、簡易ログインがあると面接側はとてもありがたいですよ 👍 
ポートフォリオの内容を確認するのに、新規登録があると登録の手間があるので。

**Comment by komachi16** [comment]
@iwaseasahi 様
動作確認ができたとのご報告、安心いたしました。ブラウザが原因では無いようなので、今後同じことが起きぬよう、原因については引き続き調べていこうと思います。
また、ポートフォリオに関するアドバイスもいただき有難うございます。簡易ログインについては勉強不足だったため、これから実装に向けて調べてまいります。

お忙しい中、ご返信いただき有難うございました。
